// Package scim provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package scim

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	Sec0Scopes = "sec0.Scopes"
)

// RetrieveResourceTypesCopyParams defines parameters for RetrieveResourceTypesCopy.
type RetrieveResourceTypesCopyParams struct {
	// StartIndex The 1-based index of the first result in the current set of list results
	StartIndex *int32 `form:"startIndex,omitempty" json:"startIndex,omitempty"`

	// Count Non-negative integer. Specifies the desired maximum number of query results per page
	Count *int32 `form:"count,omitempty" json:"count,omitempty"`

	// Filter Filter by userName. e.g. userName eq "example@example.com"
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody struct {
	// Active Used to indicate whether the identity is active (true) or deprovisioned (false).
	Active *string `json:"active,omitempty"`

	// Emails List of user emails, only primary supported and only a predefined allow list of domains are accepted.
	Emails *[]string `json:"emails,omitempty"`

	// ExternalId This identifier is generated by the SAML provider, and is used as a unique ID by the SAML provider to match against a Notarize user.
	ExternalId *string `json:"externalId,omitempty"`

	// Name The full name of the user, represented by a `name` object
	Name *struct {
		// FamilyName The last name of the user
		FamilyName *string `json:"familyName,omitempty"`

		// GivenName The first name of the user
		GivenName *string `json:"givenName,omitempty"`
	} `json:"name,omitempty"`

	// Roles List of user roles, only primary supported. One of “owner”, “admin” or “employee”.
	Roles *[]string `json:"roles,omitempty"`

	// UserName Email address as username.
	UserName string `json:"userName"`
}

// CreateUserParams defines parameters for CreateUser.
type CreateUserParams struct {
	Accept *string `json:"accept,omitempty"`
}

// ReplaceUserCopy1Params defines parameters for ReplaceUserCopy1.
type ReplaceUserCopy1Params struct {
	Accept *string `json:"accept,omitempty"`
}

// CreateUserCopyParams defines parameters for CreateUserCopy.
type CreateUserCopyParams struct {
	Accept *string `json:"accept,omitempty"`
}

// ReplaceUserCopyJSONBody defines parameters for ReplaceUserCopy.
type ReplaceUserCopyJSONBody struct {
	// Operations Set of operations to be performed
	Operations struct {
		// Op Can be one of: add, remove, replace
		Op string `json:"op"`

		// Path Path to value in resource. Top level values ("name") and child values ("name.givenName") supported.
		Path *string `json:"path,omitempty"`

		// Value Can be an object, array, or string. Value may be dependent on "path"
		Value *string `json:"value,omitempty"`
	} `json:"Operations"`
}

// ReplaceUserCopyParams defines parameters for ReplaceUserCopy.
type ReplaceUserCopyParams struct {
	Accept *string `json:"accept,omitempty"`
}

// CreateUserCopy1JSONBody defines parameters for CreateUserCopy1.
type CreateUserCopy1JSONBody struct {
	// Active Used to indicate whether the identity is active (true) or deprovisioned (false).
	Active *string `json:"active,omitempty"`

	// Emails List of user emails, only primary supported and only a predefined allow list of domains are accepted.
	Emails *[]string `json:"emails,omitempty"`

	// ExternalId This identifier is generated by the SAML provider, and is used as a unique ID by the SAML provider to match against a Notarize user.
	ExternalId *string `json:"externalId,omitempty"`

	// Name The full name of the user, represented by a `name` object
	Name *struct {
		// FamilyName The last name of the user
		FamilyName *string `json:"familyName,omitempty"`

		// GivenName The first name of the user
		GivenName *string `json:"givenName,omitempty"`
	} `json:"name,omitempty"`

	// Roles List of user roles, only primary supported. One of “owner”, “admin” or “employee”.
	Roles *[]string `json:"roles,omitempty"`

	// UserName Email address as username.
	UserName string `json:"userName"`
}

// CreateUserCopy1Params defines parameters for CreateUserCopy1.
type CreateUserCopy1Params struct {
	Accept *string `json:"accept,omitempty"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// ReplaceUserCopyJSONRequestBody defines body for ReplaceUserCopy for application/json ContentType.
type ReplaceUserCopyJSONRequestBody ReplaceUserCopyJSONBody

// CreateUserCopy1JSONRequestBody defines body for CreateUserCopy1 for application/json ContentType.
type CreateUserCopy1JSONRequestBody CreateUserCopy1JSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// RetrieveServiceProviderConfigCopy request
	RetrieveServiceProviderConfigCopy(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RetrieveUsersSchema request
	RetrieveUsersSchema(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RetrieveUsersSchemaCopy request
	RetrieveUsersSchemaCopy(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RetrieveResourceTypesCopy request
	RetrieveResourceTypesCopy(ctx context.Context, organizationId string, params *RetrieveResourceTypesCopyParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUserWithBody request with any body
	CreateUserWithBody(ctx context.Context, organizationId string, params *CreateUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateUser(ctx context.Context, organizationId string, params *CreateUserParams, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReplaceUserCopy1 request
	ReplaceUserCopy1(ctx context.Context, organizationId string, userId string, params *ReplaceUserCopy1Params, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUserCopy request
	CreateUserCopy(ctx context.Context, organizationId string, userId string, params *CreateUserCopyParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReplaceUserCopyWithBody request with any body
	ReplaceUserCopyWithBody(ctx context.Context, organizationId string, userId string, params *ReplaceUserCopyParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReplaceUserCopy(ctx context.Context, organizationId string, userId string, params *ReplaceUserCopyParams, body ReplaceUserCopyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUserCopy1WithBody request with any body
	CreateUserCopy1WithBody(ctx context.Context, organizationId string, userId string, params *CreateUserCopy1Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateUserCopy1(ctx context.Context, organizationId string, userId string, params *CreateUserCopy1Params, body CreateUserCopy1JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) RetrieveServiceProviderConfigCopy(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRetrieveServiceProviderConfigCopyRequest(c.Server, organizationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RetrieveUsersSchema(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRetrieveUsersSchemaRequest(c.Server, organizationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RetrieveUsersSchemaCopy(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRetrieveUsersSchemaCopyRequest(c.Server, organizationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RetrieveResourceTypesCopy(ctx context.Context, organizationId string, params *RetrieveResourceTypesCopyParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRetrieveResourceTypesCopyRequest(c.Server, organizationId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUserWithBody(ctx context.Context, organizationId string, params *CreateUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUserRequestWithBody(c.Server, organizationId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUser(ctx context.Context, organizationId string, params *CreateUserParams, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUserRequest(c.Server, organizationId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplaceUserCopy1(ctx context.Context, organizationId string, userId string, params *ReplaceUserCopy1Params, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceUserCopy1Request(c.Server, organizationId, userId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUserCopy(ctx context.Context, organizationId string, userId string, params *CreateUserCopyParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUserCopyRequest(c.Server, organizationId, userId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplaceUserCopyWithBody(ctx context.Context, organizationId string, userId string, params *ReplaceUserCopyParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceUserCopyRequestWithBody(c.Server, organizationId, userId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplaceUserCopy(ctx context.Context, organizationId string, userId string, params *ReplaceUserCopyParams, body ReplaceUserCopyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceUserCopyRequest(c.Server, organizationId, userId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUserCopy1WithBody(ctx context.Context, organizationId string, userId string, params *CreateUserCopy1Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUserCopy1RequestWithBody(c.Server, organizationId, userId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUserCopy1(ctx context.Context, organizationId string, userId string, params *CreateUserCopy1Params, body CreateUserCopy1JSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUserCopy1Request(c.Server, organizationId, userId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRetrieveServiceProviderConfigCopyRequest generates requests for RetrieveServiceProviderConfigCopy
func NewRetrieveServiceProviderConfigCopyRequest(server string, organizationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/ResourceTypes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRetrieveUsersSchemaRequest generates requests for RetrieveUsersSchema
func NewRetrieveUsersSchemaRequest(server string, organizationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Schemas/Users", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRetrieveUsersSchemaCopyRequest generates requests for RetrieveUsersSchemaCopy
func NewRetrieveUsersSchemaCopyRequest(server string, organizationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/ServiceProviderConfig", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRetrieveResourceTypesCopyRequest generates requests for RetrieveResourceTypesCopy
func NewRetrieveResourceTypesCopyRequest(server string, organizationId string, params *RetrieveResourceTypesCopyParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Users", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.StartIndex != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "startIndex", *params.StartIndex, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Count != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "count", *params.Count, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Filter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter", *params.Filter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateUserRequest calls the generic CreateUser builder with application/json body
func NewCreateUserRequest(server string, organizationId string, params *CreateUserParams, body CreateUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateUserRequestWithBody(server, organizationId, params, "application/json", bodyReader)
}

// NewCreateUserRequestWithBody generates requests for CreateUser with any type of body
func NewCreateUserRequestWithBody(server string, organizationId string, params *CreateUserParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Users", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept", headerParam0)
		}

	}

	return req, nil
}

// NewReplaceUserCopy1Request generates requests for ReplaceUserCopy1
func NewReplaceUserCopy1Request(server string, organizationId string, userId string, params *ReplaceUserCopy1Params) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Users/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept", headerParam0)
		}

	}

	return req, nil
}

// NewCreateUserCopyRequest generates requests for CreateUserCopy
func NewCreateUserCopyRequest(server string, organizationId string, userId string, params *CreateUserCopyParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Users/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept", headerParam0)
		}

	}

	return req, nil
}

// NewReplaceUserCopyRequest calls the generic ReplaceUserCopy builder with application/json body
func NewReplaceUserCopyRequest(server string, organizationId string, userId string, params *ReplaceUserCopyParams, body ReplaceUserCopyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReplaceUserCopyRequestWithBody(server, organizationId, userId, params, "application/json", bodyReader)
}

// NewReplaceUserCopyRequestWithBody generates requests for ReplaceUserCopy with any type of body
func NewReplaceUserCopyRequestWithBody(server string, organizationId string, userId string, params *ReplaceUserCopyParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Users/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept", headerParam0)
		}

	}

	return req, nil
}

// NewCreateUserCopy1Request calls the generic CreateUserCopy1 builder with application/json body
func NewCreateUserCopy1Request(server string, organizationId string, userId string, params *CreateUserCopy1Params, body CreateUserCopy1JSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateUserCopy1RequestWithBody(server, organizationId, userId, params, "application/json", bodyReader)
}

// NewCreateUserCopy1RequestWithBody generates requests for CreateUserCopy1 with any type of body
func NewCreateUserCopy1RequestWithBody(server string, organizationId string, userId string, params *CreateUserCopy1Params, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "organization_id", organizationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "user_id", userId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s/Users/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// RetrieveServiceProviderConfigCopyWithResponse request
	RetrieveServiceProviderConfigCopyWithResponse(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*RetrieveServiceProviderConfigCopyResponse, error)

	// RetrieveUsersSchemaWithResponse request
	RetrieveUsersSchemaWithResponse(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*RetrieveUsersSchemaResponse, error)

	// RetrieveUsersSchemaCopyWithResponse request
	RetrieveUsersSchemaCopyWithResponse(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*RetrieveUsersSchemaCopyResponse, error)

	// RetrieveResourceTypesCopyWithResponse request
	RetrieveResourceTypesCopyWithResponse(ctx context.Context, organizationId string, params *RetrieveResourceTypesCopyParams, reqEditors ...RequestEditorFn) (*RetrieveResourceTypesCopyResponse, error)

	// CreateUserWithBodyWithResponse request with any body
	CreateUserWithBodyWithResponse(ctx context.Context, organizationId string, params *CreateUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUserResponse, error)

	CreateUserWithResponse(ctx context.Context, organizationId string, params *CreateUserParams, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUserResponse, error)

	// ReplaceUserCopy1WithResponse request
	ReplaceUserCopy1WithResponse(ctx context.Context, organizationId string, userId string, params *ReplaceUserCopy1Params, reqEditors ...RequestEditorFn) (*ReplaceUserCopy1Response, error)

	// CreateUserCopyWithResponse request
	CreateUserCopyWithResponse(ctx context.Context, organizationId string, userId string, params *CreateUserCopyParams, reqEditors ...RequestEditorFn) (*CreateUserCopyResponse, error)

	// ReplaceUserCopyWithBodyWithResponse request with any body
	ReplaceUserCopyWithBodyWithResponse(ctx context.Context, organizationId string, userId string, params *ReplaceUserCopyParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplaceUserCopyResponse, error)

	ReplaceUserCopyWithResponse(ctx context.Context, organizationId string, userId string, params *ReplaceUserCopyParams, body ReplaceUserCopyJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplaceUserCopyResponse, error)

	// CreateUserCopy1WithBodyWithResponse request with any body
	CreateUserCopy1WithBodyWithResponse(ctx context.Context, organizationId string, userId string, params *CreateUserCopy1Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUserCopy1Response, error)

	CreateUserCopy1WithResponse(ctx context.Context, organizationId string, userId string, params *CreateUserCopy1Params, body CreateUserCopy1JSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUserCopy1Response, error)
}

type RetrieveServiceProviderConfigCopyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Resources *[]struct {
			Description *string `json:"description,omitempty"`
			Endpoint    *string `json:"endpoint,omitempty"`
			Id          *string `json:"id,omitempty"`
			Meta        *struct {
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name    *string   `json:"name,omitempty"`
			Schema  *string   `json:"schema,omitempty"`
			Schemas *[]string `json:"schemas,omitempty"`
		} `json:"Resources,omitempty"`
		ItemsPerPage *int      `json:"itemsPerPage,omitempty"`
		Schemas      *[]string `json:"schemas,omitempty"`
		StartIndex   *int      `json:"startIndex,omitempty"`
		TotalResults *int      `json:"totalResults,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r RetrieveServiceProviderConfigCopyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RetrieveServiceProviderConfigCopyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RetrieveUsersSchemaResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Description *string `json:"description,omitempty"`
		Properties  *struct {
			Active *struct {
				Description *string `json:"description,omitempty"`
				Examples    *[]bool `json:"examples,omitempty"`
				Type        *string `json:"type,omitempty"`
			} `json:"active,omitempty"`
			DisplayName *struct {
				Description *string   `json:"description,omitempty"`
				Examples    *[]string `json:"examples,omitempty"`
				Type        *[]string `json:"type,omitempty"`
			} `json:"displayName,omitempty"`
			Emails *struct {
				Description *string `json:"description,omitempty"`
				Examples    *[]struct {
					Primary *bool   `json:"primary,omitempty"`
					Value   *string `json:"value,omitempty"`
				} `json:"examples,omitempty"`
				Items *struct {
					Properties *struct {
						Primary *struct {
							Type *string `json:"type,omitempty"`
						} `json:"primary,omitempty"`
						Type *struct {
							Type *string `json:"type,omitempty"`
						} `json:"type,omitempty"`
						Value *struct {
							Type *string `json:"type,omitempty"`
						} `json:"value,omitempty"`
					} `json:"properties,omitempty"`
					Required *[]string `json:"required,omitempty"`
					Type     *string   `json:"type,omitempty"`
				} `json:"items,omitempty"`
				Type *string `json:"type,omitempty"`
			} `json:"emails,omitempty"`
			ExternalId *struct {
				Description *string   `json:"description,omitempty"`
				Examples    *[]string `json:"examples,omitempty"`
				Type        *[]string `json:"type,omitempty"`
			} `json:"externalId,omitempty"`
			Id *struct {
				Description *string   `json:"description,omitempty"`
				Examples    *[]string `json:"examples,omitempty"`
				Type        *string   `json:"type,omitempty"`
			} `json:"id,omitempty"`
			Meta *struct {
				Properties *struct {
					Created *struct {
						Examples *[]string `json:"examples,omitempty"`
						Format   *string   `json:"format,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"created,omitempty"`
					LastModified *struct {
						Examples *[]string `json:"examples,omitempty"`
						Format   *string   `json:"format,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"lastModified,omitempty"`
					Location *struct {
						Examples *[]string `json:"examples,omitempty"`
						Format   *string   `json:"format,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"location,omitempty"`
					ResourceType *struct {
						Examples *[]string `json:"examples,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"resourceType,omitempty"`
				} `json:"properties,omitempty"`
				Type *string `json:"type,omitempty"`
			} `json:"meta,omitempty"`
			Name *struct {
				Example *struct {
					FamilyName *string `json:"familyName,omitempty"`
					GivenName  *string `json:"givenName,omitempty"`
				} `json:"example,omitempty"`
				Properties *struct {
					FamilyName *struct {
						Type *[]string `json:"type,omitempty"`
					} `json:"familyName,omitempty"`
					GivenName *struct {
						Type *[]string `json:"type,omitempty"`
					} `json:"givenName,omitempty"`
				} `json:"properties,omitempty"`
				Type *string `json:"type,omitempty"`
			} `json:"name,omitempty"`
			Operations *struct {
				Description *string `json:"description,omitempty"`
				Examples    *[]struct {
					Op    *string `json:"op,omitempty"`
					Value *struct {
						Active *bool `json:"active,omitempty"`
					} `json:"value,omitempty"`
				} `json:"examples,omitempty"`
				Items *struct {
					Properties *struct {
						Op *struct {
							Enum *[]string `json:"enum,omitempty"`
							Type *string   `json:"type,omitempty"`
						} `json:"op,omitempty"`
						Path *struct {
							Type *string `json:"type,omitempty"`
						} `json:"path,omitempty"`
						Value *struct {
							OneOf *[]struct {
								Type *string `json:"type,omitempty"`
							} `json:"oneOf,omitempty"`
						} `json:"value,omitempty"`
					} `json:"properties,omitempty"`
					Required *[]string `json:"required,omitempty"`
					Type     *string   `json:"type,omitempty"`
				} `json:"items,omitempty"`
				MinItems *int    `json:"minItems,omitempty"`
				Type     *string `json:"type,omitempty"`
			} `json:"operations,omitempty"`
			Roles *struct {
				Items *struct {
					Properties *struct {
						Display *struct {
							Type *string `json:"type,omitempty"`
						} `json:"display,omitempty"`
						Primary *struct {
							Type *string `json:"type,omitempty"`
						} `json:"primary,omitempty"`
						Value *struct {
							Type *string `json:"type,omitempty"`
						} `json:"value,omitempty"`
					} `json:"properties,omitempty"`
					Type *string `json:"type,omitempty"`
				} `json:"items,omitempty"`
				Type *string `json:"type,omitempty"`
			} `json:"roles,omitempty"`
			Schemas *struct {
				Description *string `json:"description,omitempty"`
				Items       *struct {
					Examples *[]string `json:"examples,omitempty"`
					Type     *string   `json:"type,omitempty"`
				} `json:"items,omitempty"`
				MinItems *int    `json:"minItems,omitempty"`
				Type     *string `json:"type,omitempty"`
			} `json:"schemas,omitempty"`
			UserName *struct {
				Description *string   `json:"description,omitempty"`
				Examples    *[]string `json:"examples,omitempty"`
				Type        *[]string `json:"type,omitempty"`
			} `json:"userName,omitempty"`
		} `json:"properties,omitempty"`
		Required *[]string `json:"required,omitempty"`
		Title    *string   `json:"title,omitempty"`
		Type     *string   `json:"type,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r RetrieveUsersSchemaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RetrieveUsersSchemaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RetrieveUsersSchemaCopyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		AuthenticationSchemes *[]struct {
			Description      *string `json:"description,omitempty"`
			DocumentationUri *string `json:"documentationUri,omitempty"`
			Name             *string `json:"name,omitempty"`
			Primary          *bool   `json:"primary,omitempty"`
			Type             *string `json:"type,omitempty"`
		} `json:"authenticationSchemes,omitempty"`
		Bulk *struct {
			Supported *bool `json:"supported,omitempty"`
		} `json:"bulk,omitempty"`
		ChangePassword *struct {
			Supported *bool `json:"supported,omitempty"`
		} `json:"changePassword,omitempty"`
		DocumentationUri *string `json:"documentationUri,omitempty"`
		Etag             *struct {
			Supported *bool `json:"supported,omitempty"`
		} `json:"etag,omitempty"`
		Filter *struct {
			Supported *bool `json:"supported,omitempty"`
		} `json:"filter,omitempty"`
		Meta *struct {
			Location     *string `json:"location,omitempty"`
			ResourceType *string `json:"resourceType,omitempty"`
		} `json:"meta,omitempty"`
		Name  *string `json:"name,omitempty"`
		Patch *struct {
			Supported *bool `json:"supported,omitempty"`
		} `json:"patch,omitempty"`
		Schemas *[]string `json:"schemas,omitempty"`
		Sort    *struct {
			Supported *bool `json:"supported,omitempty"`
		} `json:"sort,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r RetrieveUsersSchemaCopyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RetrieveUsersSchemaCopyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RetrieveResourceTypesCopyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Resources *[]struct {
			Active *bool `json:"active,omitempty"`
			Emails *[]struct {
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"emails,omitempty"`
			ExternalId interface{} `json:"externalId,omitempty"`
			Id         *string     `json:"id,omitempty"`
			Meta       *struct {
				Created      *string `json:"created,omitempty"`
				LastModified *string `json:"lastModified,omitempty"`
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name *struct {
				FamilyName *string `json:"familyName,omitempty"`
				GivenName  *string `json:"givenName,omitempty"`
			} `json:"name,omitempty"`
			Roles *[]struct {
				Display *string `json:"display,omitempty"`
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"roles,omitempty"`
			Schemas  *[]string `json:"schemas,omitempty"`
			UserName *string   `json:"userName,omitempty"`
		} `json:"Resources,omitempty"`
		ItemsPerPage *int      `json:"itemsPerPage,omitempty"`
		Schemas      *[]string `json:"schemas,omitempty"`
		StartIndex   *int      `json:"startIndex,omitempty"`
		TotalResults *int      `json:"totalResults,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r RetrieveResourceTypesCopyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RetrieveResourceTypesCopyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Active *bool `json:"active,omitempty"`
		Emails *[]struct {
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"emails,omitempty"`
		ExternalId *string `json:"externalId,omitempty"`
		Id         *string `json:"id,omitempty"`
		Meta       *struct {
			Created      *string `json:"created,omitempty"`
			LastModified *string `json:"lastModified,omitempty"`
			Location     *string `json:"location,omitempty"`
			ResourceType *string `json:"resourceType,omitempty"`
		} `json:"meta,omitempty"`
		Name *struct {
			FamilyName *string `json:"familyName,omitempty"`
			GivenName  *string `json:"givenName,omitempty"`
		} `json:"name,omitempty"`
		Roles *[]struct {
			Display *string `json:"display,omitempty"`
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"roles,omitempty"`
		Schemas  *[]string `json:"schemas,omitempty"`
		UserName *string   `json:"userName,omitempty"`
	}
	JSON400 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreateUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReplaceUserCopy1Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON204      *map[string]interface{}
	JSON403      *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON422 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ReplaceUserCopy1Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReplaceUserCopy1Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateUserCopyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Active *bool `json:"active,omitempty"`
		Emails *[]struct {
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"emails,omitempty"`
		ExternalId *string `json:"externalId,omitempty"`
		Id         *string `json:"id,omitempty"`
		Meta       *struct {
			Created      *string `json:"created,omitempty"`
			LastModified *string `json:"lastModified,omitempty"`
			Location     *string `json:"location,omitempty"`
			ResourceType *string `json:"resourceType,omitempty"`
		} `json:"meta,omitempty"`
		Name *struct {
			FamilyName *string `json:"familyName,omitempty"`
			GivenName  *string `json:"givenName,omitempty"`
		} `json:"name,omitempty"`
		Roles *[]struct {
			Display *string `json:"display,omitempty"`
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"roles,omitempty"`
		Schemas  *[]string `json:"schemas,omitempty"`
		UserName *string   `json:"userName,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreateUserCopyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUserCopyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReplaceUserCopyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Active *bool `json:"active,omitempty"`
		Emails *[]struct {
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"emails,omitempty"`
		ExternalId *string `json:"externalId,omitempty"`
		Id         *string `json:"id,omitempty"`
		Meta       *struct {
			Created      *string `json:"created,omitempty"`
			LastModified *string `json:"lastModified,omitempty"`
			Location     *string `json:"location,omitempty"`
			ResourceType *string `json:"resourceType,omitempty"`
		} `json:"meta,omitempty"`
		Name *struct {
			FamilyName *string `json:"familyName,omitempty"`
			GivenName  *string `json:"givenName,omitempty"`
		} `json:"name,omitempty"`
		Roles *[]struct {
			Display *string `json:"display,omitempty"`
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"roles,omitempty"`
		Schemas  *[]string `json:"schemas,omitempty"`
		UserName *string   `json:"userName,omitempty"`
	}
	JSON400 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ReplaceUserCopyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReplaceUserCopyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateUserCopy1Response struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Active *bool `json:"active,omitempty"`
		Emails *[]struct {
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"emails,omitempty"`
		ExternalId *string `json:"externalId,omitempty"`
		Id         *string `json:"id,omitempty"`
		Meta       *struct {
			Created      *string `json:"created,omitempty"`
			LastModified *string `json:"lastModified,omitempty"`
			Location     *string `json:"location,omitempty"`
			ResourceType *string `json:"resourceType,omitempty"`
		} `json:"meta,omitempty"`
		Name *struct {
			FamilyName *string `json:"familyName,omitempty"`
			GivenName  *string `json:"givenName,omitempty"`
		} `json:"name,omitempty"`
		Roles *[]struct {
			Display *string `json:"display,omitempty"`
			Primary *bool   `json:"primary,omitempty"`
			Value   *string `json:"value,omitempty"`
		} `json:"roles,omitempty"`
		Schemas  *[]string `json:"schemas,omitempty"`
		UserName *string   `json:"userName,omitempty"`
	}
	JSON400 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON403 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
	JSON404 *struct {
		Errors *[]string `json:"errors,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r CreateUserCopy1Response) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUserCopy1Response) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// RetrieveServiceProviderConfigCopyWithResponse request returning *RetrieveServiceProviderConfigCopyResponse
func (c *ClientWithResponses) RetrieveServiceProviderConfigCopyWithResponse(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*RetrieveServiceProviderConfigCopyResponse, error) {
	rsp, err := c.RetrieveServiceProviderConfigCopy(ctx, organizationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRetrieveServiceProviderConfigCopyResponse(rsp)
}

// RetrieveUsersSchemaWithResponse request returning *RetrieveUsersSchemaResponse
func (c *ClientWithResponses) RetrieveUsersSchemaWithResponse(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*RetrieveUsersSchemaResponse, error) {
	rsp, err := c.RetrieveUsersSchema(ctx, organizationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRetrieveUsersSchemaResponse(rsp)
}

// RetrieveUsersSchemaCopyWithResponse request returning *RetrieveUsersSchemaCopyResponse
func (c *ClientWithResponses) RetrieveUsersSchemaCopyWithResponse(ctx context.Context, organizationId string, reqEditors ...RequestEditorFn) (*RetrieveUsersSchemaCopyResponse, error) {
	rsp, err := c.RetrieveUsersSchemaCopy(ctx, organizationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRetrieveUsersSchemaCopyResponse(rsp)
}

// RetrieveResourceTypesCopyWithResponse request returning *RetrieveResourceTypesCopyResponse
func (c *ClientWithResponses) RetrieveResourceTypesCopyWithResponse(ctx context.Context, organizationId string, params *RetrieveResourceTypesCopyParams, reqEditors ...RequestEditorFn) (*RetrieveResourceTypesCopyResponse, error) {
	rsp, err := c.RetrieveResourceTypesCopy(ctx, organizationId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRetrieveResourceTypesCopyResponse(rsp)
}

// CreateUserWithBodyWithResponse request with arbitrary body returning *CreateUserResponse
func (c *ClientWithResponses) CreateUserWithBodyWithResponse(ctx context.Context, organizationId string, params *CreateUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUserResponse, error) {
	rsp, err := c.CreateUserWithBody(ctx, organizationId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUserResponse(rsp)
}

func (c *ClientWithResponses) CreateUserWithResponse(ctx context.Context, organizationId string, params *CreateUserParams, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUserResponse, error) {
	rsp, err := c.CreateUser(ctx, organizationId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUserResponse(rsp)
}

// ReplaceUserCopy1WithResponse request returning *ReplaceUserCopy1Response
func (c *ClientWithResponses) ReplaceUserCopy1WithResponse(ctx context.Context, organizationId string, userId string, params *ReplaceUserCopy1Params, reqEditors ...RequestEditorFn) (*ReplaceUserCopy1Response, error) {
	rsp, err := c.ReplaceUserCopy1(ctx, organizationId, userId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplaceUserCopy1Response(rsp)
}

// CreateUserCopyWithResponse request returning *CreateUserCopyResponse
func (c *ClientWithResponses) CreateUserCopyWithResponse(ctx context.Context, organizationId string, userId string, params *CreateUserCopyParams, reqEditors ...RequestEditorFn) (*CreateUserCopyResponse, error) {
	rsp, err := c.CreateUserCopy(ctx, organizationId, userId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUserCopyResponse(rsp)
}

// ReplaceUserCopyWithBodyWithResponse request with arbitrary body returning *ReplaceUserCopyResponse
func (c *ClientWithResponses) ReplaceUserCopyWithBodyWithResponse(ctx context.Context, organizationId string, userId string, params *ReplaceUserCopyParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplaceUserCopyResponse, error) {
	rsp, err := c.ReplaceUserCopyWithBody(ctx, organizationId, userId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplaceUserCopyResponse(rsp)
}

func (c *ClientWithResponses) ReplaceUserCopyWithResponse(ctx context.Context, organizationId string, userId string, params *ReplaceUserCopyParams, body ReplaceUserCopyJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplaceUserCopyResponse, error) {
	rsp, err := c.ReplaceUserCopy(ctx, organizationId, userId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplaceUserCopyResponse(rsp)
}

// CreateUserCopy1WithBodyWithResponse request with arbitrary body returning *CreateUserCopy1Response
func (c *ClientWithResponses) CreateUserCopy1WithBodyWithResponse(ctx context.Context, organizationId string, userId string, params *CreateUserCopy1Params, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUserCopy1Response, error) {
	rsp, err := c.CreateUserCopy1WithBody(ctx, organizationId, userId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUserCopy1Response(rsp)
}

func (c *ClientWithResponses) CreateUserCopy1WithResponse(ctx context.Context, organizationId string, userId string, params *CreateUserCopy1Params, body CreateUserCopy1JSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUserCopy1Response, error) {
	rsp, err := c.CreateUserCopy1(ctx, organizationId, userId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUserCopy1Response(rsp)
}

// ParseRetrieveServiceProviderConfigCopyResponse parses an HTTP response from a RetrieveServiceProviderConfigCopyWithResponse call
func ParseRetrieveServiceProviderConfigCopyResponse(rsp *http.Response) (*RetrieveServiceProviderConfigCopyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RetrieveServiceProviderConfigCopyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Resources *[]struct {
				Description *string `json:"description,omitempty"`
				Endpoint    *string `json:"endpoint,omitempty"`
				Id          *string `json:"id,omitempty"`
				Meta        *struct {
					Location     *string `json:"location,omitempty"`
					ResourceType *string `json:"resourceType,omitempty"`
				} `json:"meta,omitempty"`
				Name    *string   `json:"name,omitempty"`
				Schema  *string   `json:"schema,omitempty"`
				Schemas *[]string `json:"schemas,omitempty"`
			} `json:"Resources,omitempty"`
			ItemsPerPage *int      `json:"itemsPerPage,omitempty"`
			Schemas      *[]string `json:"schemas,omitempty"`
			StartIndex   *int      `json:"startIndex,omitempty"`
			TotalResults *int      `json:"totalResults,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseRetrieveUsersSchemaResponse parses an HTTP response from a RetrieveUsersSchemaWithResponse call
func ParseRetrieveUsersSchemaResponse(rsp *http.Response) (*RetrieveUsersSchemaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RetrieveUsersSchemaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Description *string `json:"description,omitempty"`
			Properties  *struct {
				Active *struct {
					Description *string `json:"description,omitempty"`
					Examples    *[]bool `json:"examples,omitempty"`
					Type        *string `json:"type,omitempty"`
				} `json:"active,omitempty"`
				DisplayName *struct {
					Description *string   `json:"description,omitempty"`
					Examples    *[]string `json:"examples,omitempty"`
					Type        *[]string `json:"type,omitempty"`
				} `json:"displayName,omitempty"`
				Emails *struct {
					Description *string `json:"description,omitempty"`
					Examples    *[]struct {
						Primary *bool   `json:"primary,omitempty"`
						Value   *string `json:"value,omitempty"`
					} `json:"examples,omitempty"`
					Items *struct {
						Properties *struct {
							Primary *struct {
								Type *string `json:"type,omitempty"`
							} `json:"primary,omitempty"`
							Type *struct {
								Type *string `json:"type,omitempty"`
							} `json:"type,omitempty"`
							Value *struct {
								Type *string `json:"type,omitempty"`
							} `json:"value,omitempty"`
						} `json:"properties,omitempty"`
						Required *[]string `json:"required,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"items,omitempty"`
					Type *string `json:"type,omitempty"`
				} `json:"emails,omitempty"`
				ExternalId *struct {
					Description *string   `json:"description,omitempty"`
					Examples    *[]string `json:"examples,omitempty"`
					Type        *[]string `json:"type,omitempty"`
				} `json:"externalId,omitempty"`
				Id *struct {
					Description *string   `json:"description,omitempty"`
					Examples    *[]string `json:"examples,omitempty"`
					Type        *string   `json:"type,omitempty"`
				} `json:"id,omitempty"`
				Meta *struct {
					Properties *struct {
						Created *struct {
							Examples *[]string `json:"examples,omitempty"`
							Format   *string   `json:"format,omitempty"`
							Type     *string   `json:"type,omitempty"`
						} `json:"created,omitempty"`
						LastModified *struct {
							Examples *[]string `json:"examples,omitempty"`
							Format   *string   `json:"format,omitempty"`
							Type     *string   `json:"type,omitempty"`
						} `json:"lastModified,omitempty"`
						Location *struct {
							Examples *[]string `json:"examples,omitempty"`
							Format   *string   `json:"format,omitempty"`
							Type     *string   `json:"type,omitempty"`
						} `json:"location,omitempty"`
						ResourceType *struct {
							Examples *[]string `json:"examples,omitempty"`
							Type     *string   `json:"type,omitempty"`
						} `json:"resourceType,omitempty"`
					} `json:"properties,omitempty"`
					Type *string `json:"type,omitempty"`
				} `json:"meta,omitempty"`
				Name *struct {
					Example *struct {
						FamilyName *string `json:"familyName,omitempty"`
						GivenName  *string `json:"givenName,omitempty"`
					} `json:"example,omitempty"`
					Properties *struct {
						FamilyName *struct {
							Type *[]string `json:"type,omitempty"`
						} `json:"familyName,omitempty"`
						GivenName *struct {
							Type *[]string `json:"type,omitempty"`
						} `json:"givenName,omitempty"`
					} `json:"properties,omitempty"`
					Type *string `json:"type,omitempty"`
				} `json:"name,omitempty"`
				Operations *struct {
					Description *string `json:"description,omitempty"`
					Examples    *[]struct {
						Op    *string `json:"op,omitempty"`
						Value *struct {
							Active *bool `json:"active,omitempty"`
						} `json:"value,omitempty"`
					} `json:"examples,omitempty"`
					Items *struct {
						Properties *struct {
							Op *struct {
								Enum *[]string `json:"enum,omitempty"`
								Type *string   `json:"type,omitempty"`
							} `json:"op,omitempty"`
							Path *struct {
								Type *string `json:"type,omitempty"`
							} `json:"path,omitempty"`
							Value *struct {
								OneOf *[]struct {
									Type *string `json:"type,omitempty"`
								} `json:"oneOf,omitempty"`
							} `json:"value,omitempty"`
						} `json:"properties,omitempty"`
						Required *[]string `json:"required,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"items,omitempty"`
					MinItems *int    `json:"minItems,omitempty"`
					Type     *string `json:"type,omitempty"`
				} `json:"operations,omitempty"`
				Roles *struct {
					Items *struct {
						Properties *struct {
							Display *struct {
								Type *string `json:"type,omitempty"`
							} `json:"display,omitempty"`
							Primary *struct {
								Type *string `json:"type,omitempty"`
							} `json:"primary,omitempty"`
							Value *struct {
								Type *string `json:"type,omitempty"`
							} `json:"value,omitempty"`
						} `json:"properties,omitempty"`
						Type *string `json:"type,omitempty"`
					} `json:"items,omitempty"`
					Type *string `json:"type,omitempty"`
				} `json:"roles,omitempty"`
				Schemas *struct {
					Description *string `json:"description,omitempty"`
					Items       *struct {
						Examples *[]string `json:"examples,omitempty"`
						Type     *string   `json:"type,omitempty"`
					} `json:"items,omitempty"`
					MinItems *int    `json:"minItems,omitempty"`
					Type     *string `json:"type,omitempty"`
				} `json:"schemas,omitempty"`
				UserName *struct {
					Description *string   `json:"description,omitempty"`
					Examples    *[]string `json:"examples,omitempty"`
					Type        *[]string `json:"type,omitempty"`
				} `json:"userName,omitempty"`
			} `json:"properties,omitempty"`
			Required *[]string `json:"required,omitempty"`
			Title    *string   `json:"title,omitempty"`
			Type     *string   `json:"type,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseRetrieveUsersSchemaCopyResponse parses an HTTP response from a RetrieveUsersSchemaCopyWithResponse call
func ParseRetrieveUsersSchemaCopyResponse(rsp *http.Response) (*RetrieveUsersSchemaCopyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RetrieveUsersSchemaCopyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			AuthenticationSchemes *[]struct {
				Description      *string `json:"description,omitempty"`
				DocumentationUri *string `json:"documentationUri,omitempty"`
				Name             *string `json:"name,omitempty"`
				Primary          *bool   `json:"primary,omitempty"`
				Type             *string `json:"type,omitempty"`
			} `json:"authenticationSchemes,omitempty"`
			Bulk *struct {
				Supported *bool `json:"supported,omitempty"`
			} `json:"bulk,omitempty"`
			ChangePassword *struct {
				Supported *bool `json:"supported,omitempty"`
			} `json:"changePassword,omitempty"`
			DocumentationUri *string `json:"documentationUri,omitempty"`
			Etag             *struct {
				Supported *bool `json:"supported,omitempty"`
			} `json:"etag,omitempty"`
			Filter *struct {
				Supported *bool `json:"supported,omitempty"`
			} `json:"filter,omitempty"`
			Meta *struct {
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name  *string `json:"name,omitempty"`
			Patch *struct {
				Supported *bool `json:"supported,omitempty"`
			} `json:"patch,omitempty"`
			Schemas *[]string `json:"schemas,omitempty"`
			Sort    *struct {
				Supported *bool `json:"supported,omitempty"`
			} `json:"sort,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseRetrieveResourceTypesCopyResponse parses an HTTP response from a RetrieveResourceTypesCopyWithResponse call
func ParseRetrieveResourceTypesCopyResponse(rsp *http.Response) (*RetrieveResourceTypesCopyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RetrieveResourceTypesCopyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Resources *[]struct {
				Active *bool `json:"active,omitempty"`
				Emails *[]struct {
					Primary *bool   `json:"primary,omitempty"`
					Value   *string `json:"value,omitempty"`
				} `json:"emails,omitempty"`
				ExternalId interface{} `json:"externalId,omitempty"`
				Id         *string     `json:"id,omitempty"`
				Meta       *struct {
					Created      *string `json:"created,omitempty"`
					LastModified *string `json:"lastModified,omitempty"`
					Location     *string `json:"location,omitempty"`
					ResourceType *string `json:"resourceType,omitempty"`
				} `json:"meta,omitempty"`
				Name *struct {
					FamilyName *string `json:"familyName,omitempty"`
					GivenName  *string `json:"givenName,omitempty"`
				} `json:"name,omitempty"`
				Roles *[]struct {
					Display *string `json:"display,omitempty"`
					Primary *bool   `json:"primary,omitempty"`
					Value   *string `json:"value,omitempty"`
				} `json:"roles,omitempty"`
				Schemas  *[]string `json:"schemas,omitempty"`
				UserName *string   `json:"userName,omitempty"`
			} `json:"Resources,omitempty"`
			ItemsPerPage *int      `json:"itemsPerPage,omitempty"`
			Schemas      *[]string `json:"schemas,omitempty"`
			StartIndex   *int      `json:"startIndex,omitempty"`
			TotalResults *int      `json:"totalResults,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCreateUserResponse parses an HTTP response from a CreateUserWithResponse call
func ParseCreateUserResponse(rsp *http.Response) (*CreateUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Active *bool `json:"active,omitempty"`
			Emails *[]struct {
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"emails,omitempty"`
			ExternalId *string `json:"externalId,omitempty"`
			Id         *string `json:"id,omitempty"`
			Meta       *struct {
				Created      *string `json:"created,omitempty"`
				LastModified *string `json:"lastModified,omitempty"`
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name *struct {
				FamilyName *string `json:"familyName,omitempty"`
				GivenName  *string `json:"givenName,omitempty"`
			} `json:"name,omitempty"`
			Roles *[]struct {
				Display *string `json:"display,omitempty"`
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"roles,omitempty"`
			Schemas  *[]string `json:"schemas,omitempty"`
			UserName *string   `json:"userName,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseReplaceUserCopy1Response parses an HTTP response from a ReplaceUserCopy1WithResponse call
func ParseReplaceUserCopy1Response(rsp *http.Response) (*ReplaceUserCopy1Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReplaceUserCopy1Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 204:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON204 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCreateUserCopyResponse parses an HTTP response from a CreateUserCopyWithResponse call
func ParseCreateUserCopyResponse(rsp *http.Response) (*CreateUserCopyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUserCopyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Active *bool `json:"active,omitempty"`
			Emails *[]struct {
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"emails,omitempty"`
			ExternalId *string `json:"externalId,omitempty"`
			Id         *string `json:"id,omitempty"`
			Meta       *struct {
				Created      *string `json:"created,omitempty"`
				LastModified *string `json:"lastModified,omitempty"`
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name *struct {
				FamilyName *string `json:"familyName,omitempty"`
				GivenName  *string `json:"givenName,omitempty"`
			} `json:"name,omitempty"`
			Roles *[]struct {
				Display *string `json:"display,omitempty"`
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"roles,omitempty"`
			Schemas  *[]string `json:"schemas,omitempty"`
			UserName *string   `json:"userName,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseReplaceUserCopyResponse parses an HTTP response from a ReplaceUserCopyWithResponse call
func ParseReplaceUserCopyResponse(rsp *http.Response) (*ReplaceUserCopyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReplaceUserCopyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Active *bool `json:"active,omitempty"`
			Emails *[]struct {
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"emails,omitempty"`
			ExternalId *string `json:"externalId,omitempty"`
			Id         *string `json:"id,omitempty"`
			Meta       *struct {
				Created      *string `json:"created,omitempty"`
				LastModified *string `json:"lastModified,omitempty"`
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name *struct {
				FamilyName *string `json:"familyName,omitempty"`
				GivenName  *string `json:"givenName,omitempty"`
			} `json:"name,omitempty"`
			Roles *[]struct {
				Display *string `json:"display,omitempty"`
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"roles,omitempty"`
			Schemas  *[]string `json:"schemas,omitempty"`
			UserName *string   `json:"userName,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseCreateUserCopy1Response parses an HTTP response from a CreateUserCopy1WithResponse call
func ParseCreateUserCopy1Response(rsp *http.Response) (*CreateUserCopy1Response, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUserCopy1Response{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Active *bool `json:"active,omitempty"`
			Emails *[]struct {
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"emails,omitempty"`
			ExternalId *string `json:"externalId,omitempty"`
			Id         *string `json:"id,omitempty"`
			Meta       *struct {
				Created      *string `json:"created,omitempty"`
				LastModified *string `json:"lastModified,omitempty"`
				Location     *string `json:"location,omitempty"`
				ResourceType *string `json:"resourceType,omitempty"`
			} `json:"meta,omitempty"`
			Name *struct {
				FamilyName *string `json:"familyName,omitempty"`
				GivenName  *string `json:"givenName,omitempty"`
			} `json:"name,omitempty"`
			Roles *[]struct {
				Display *string `json:"display,omitempty"`
				Primary *bool   `json:"primary,omitempty"`
				Value   *string `json:"value,omitempty"`
			} `json:"roles,omitempty"`
			Schemas  *[]string `json:"schemas,omitempty"`
			UserName *string   `json:"userName,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest struct {
			Errors *[]string `json:"errors,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
